Fixed prompt characters

diff --git a/_support/lesson b/_support/lesson
--- a/_support/lesson
+++ b/_support/lesson
@@ -26,16 +26,13 @@ echo "${cblue}***** New Lesson *****${cnone}"
 echo "Please read the ${cred}README${cnone} for guidelines!"
 echo
 echo "Enter the lesson's topic (${cgreen}ex: terminal-usage${cnone}):"
-echo -n "${cwhiteb}>${cnone} "
-read -e topic
+read -e -p "${cwhiteb}>${cnone} " topic
 
 echo "Enter the lesson's title (${cgreen}ex: \"Using Files & Commands\"${cnone}):"
-echo -n "${cwhiteb}>${cnone} "
-read -e title
+read -e -p "${cwhiteb}>${cnone} " title
 
 echo "Enter the title's slug (${cgreen}ex: files-commands${cnone}):"
-echo -n "${cwhiteb}>${cnone} "
-read -e slug
+read -e -p "${cwhiteb}>${cnone} " slug
 
 order=$(find topics/$topic/*/ -type f 2> /dev/null | xargs cat | grep 'order:' | sort -r | head -n 1 | cut -c 8-)
 if [ -z "$order" ]; then
@@ -46,6 +43,11 @@ let "next = $order + 1"
 echo
 echo "Creating new lesson..."
 octopress new page topics/$topic/$slug/ --title "$title" --template lesson
+
+if [ "$?" != 0]; then
+  echo "${cred}Error creating lesson page.${cnone}"
+  exit 1
+fi
 
 cp topics/$topic/$slug/index.md topics/$topic/$slug/index.md.tmp
 
diff --git a/_support/topic b/_support/topic
--- a/_support/topic
+++ b/_support/topic
@@ -26,12 +26,10 @@ echo "${cblue}***** New Topic *****${cnone}"
 echo "Please read the ${cred}README${cnone} for guidelines!"
 echo
 echo "Enter the topic's slug (${cgreen}ex: terminal-usage${cnone}):"
-echo -n "${cwhiteb}>${cnone} "
-read -e topic
+read -e -p "${cwhiteb}>${cnone} " topic
 
 echo "Enter the topic's title (${cgreen}ex: \"Terminal Usage\"${cnone}):"
-echo -n "${cwhiteb}>${cnone} "
-read -e title
+read -e -p "${cwhiteb}>${cnone} " title
 
 order=$(cat topics/*/index.md | grep 'order:' | sort -r | head -n 1 | cut -c 8-)
 if [ -z "$order" ]; then
@@ -42,6 +40,11 @@ let "next = $order + 1"
 echo
 echo "Creating new topic..."
 octopress new page topics/$topic/ --title "$title" --template topic
+
+if [ "$?" != 0]; then
+  echo "${cred}Error creating lesson page.${cnone}"
+  exit 1
+fi
 
 cp topics/$topic/index.md topics/$topic/index.md.tmp
 
